const tasks = [
  {
    id: 1,
    title: "Learn TanStack Query",
    description: "Master data fetching and caching",
    completed: false,
    priority: "high",
    createdAt: new Date(),
  },
  {
    id: 2,
    title: "Understand tRPC",
    description: "Build type-safe APIs",
    completed: false,
    priority: "medium",
    createdAt: new Date(),
  },
];

export const indianCities = [
  "Delhi",
  "Mumbai",
  "Chennai",
  "Kolkata",
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Bhopal",
  "Chandigarh",
  "Coimbatore",
  "Visakhapatnam",
  "Kochi",
  "Nagpur",
  "Indore",
  "Thiruvananthapuram",
  "Guwahati",
  "Varanasi",
];
